######################################################################
# Automatically generated by qmake (3.0) Thu Mar 31 13:43:31 2016
######################################################################

TEMPLATE = app
TARGET = login_test
INCLUDEPATH += ../../include 

DESTDIR = ../../bin
OBJECTS_DIR = ../../obj
MOC_DIR = ../../temp

QT += widgets printsupport


# Input
HEADERS +=  ../../include/ui/interface.hpp\
            ../../include/ui/newWindow.hpp
SOURCES +=  interface.cpp\
            newWindow.cpp\
            test.cpp 
